### ISSUE TITLE
Config file can't be opened because of malformed file path on Windows

### ISSUE THREAD

**Issue by flawiddsouza** [stretto-editor/stretto#3]
The bug is in stretto/config.go:
`file, e := ioutil.ReadFile(usr.HomeDir + "/.stretto.json")`
Here path/filepath should be used to join two paths instead of adding the forward slash, so that there are no issues on different OSs.
Fix:
```
import "path/filepath"
file, e := ioutil.ReadFile(filepath.Join(usr.HomeDir, ".stretto.json"))
```
The path formed on my computer was: `C:\Users\MyUsername/.stretto.json`
What should've been formed was: `C:\Users\MyUsername\.stretto.json`

**Comment by eric-burel** [comment]
Hi,

Thanks for the feedback. I'll try to fix ASAP.
Yet, please notice that Stretto was a (very cool) student project and thus won't be maintained actively (all the more that Atom editor last version fixes the bugs that first lead me to initiate the Stretto project).

Can I ask you where you discovered Stretto :) ?

**Comment by eric-burel** [comment]
I pushed your fix, could you please tell me if everything is okay now for you ? Thanks again

**Comment by flawiddsouza** [comment]
I discovered this project by following your link from https://neovim.io/news/2016/11/
"Eric [wrote about the experience](https://medium.com/@eric.burel/stop-using-open-source-5cb19baca44d#.4gz835f9y). Thanks to Eric, the students at ENSIMAG, @KillTheMule, and @bfredl for carrying this feature to a conclusion we are proud of."

It's fine if it's not maintained. I was just checking it out.

Yes, it works now. 😄

**Comment by eric-burel** [comment]
I definitely had a strong Text Editor period ^^. Thanks for the report.
